# Please insert new items alphabetically.

devops:
  members:
    - andrevdh
    - mafonso
    - nadirollo
    - trcrichardson
    - blaffoy
    - hernan82arg
    - dwardu89

  channel:
    "#devops-prs"

  exclude_titles:
    - "[DO NOT MERGE]"
    - "Don't merge"
    - DO NOT MERGE
    - "Waiting on factcheck"
    - WIP

  use_labels: true

  exclude_labels:
    - "work in progress"
    - "WIP"
    - "work_in_progress"
